#******************************************************************************
#*Copyright (C) 2023 by Salvador Z                                            *
#*                                                                            *
#*****************************************************************************/
#*
#*@author Salvador Z
#*@brief GitHub workflow to configure an automated process to run one or more jobs
#*
# Template for all jobs

name: Jupyter_Notebook_Testing

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches:
      - master
    types:
      - closed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      
      - name: Install dependencies
        run: pip install nbconvert numpy matplotlib

      - name: Run Jupyter Notebook tests
        run: |
          cd notebook_jupyter
          jupyter nbconvert --execute --inplace *.ipynb
          if [ $? -eq 0 ]; then
            echo "Jupyter Notebook tests passed"
          else
            echo "Jupyter Notebook tests failed"
            exit 1
          fi
